apiVersion: v1
kind: Service
metadata:
  name: vouch
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: vouch
  type: LoadBalancer
#  type: ClusterIP
  