apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - namespace.yaml
#  - loki.yaml
  
#  - origintls.yaml
#  - ingress.yaml

helmCharts:
- name: loki
  repo: https://grafana.github.io/helm-charts
  version: "6.6.3"
  releaseName: loki
  namespace: loki
  valuesFile: values.yaml

