apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-unifi-lhpv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhornscbf
  volumeMode: Filesystem
