apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp2
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi"
spec:
  loadBalancerIP: 172.16.30.200
#  allocateLoadBalancerNodePorts: true
#  externalTrafficPolicy: Cluster
#  internalTrafficPolicy: Cluster
#  ipFamilies:
#  - IPv4
#  ipFamilyPolicy: SingleStack
  ports:
  - name: udp10001
    port: 10001
    protocol: UDP
    targetPort: udp10001
  - name: udp3478
    port: 3478
    protocol: UDP
    targetPort: udp3478

  selector:
    app: unifi-controller
  type: LoadBalancer
