apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: unifi-controller
  serviceName: unifi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - name: unifi-controller
        image: jacobalberty/unifi:v8.1
        #image: lscr.io/linuxserver/unifi-controller:7.4.162
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        ports:
        - containerPort: 8081
          name: http8081
        - containerPort: 8080
          name: http8080
        - containerPort: 8443
          name: http8443
        - containerPort: 8843
          name: http8843
        - containerPort: 3478
          name: http3478
        - containerPort: 8880
          name: http8880
        - containerPort: 10001
          name: udp10001
          protocol: UDP
        - containerPort: 3478
          name: udp3478
          protocol: UDP
        volumeMounts:
        - mountPath: /unifi
          name: unifi
        - mountPath: /config
          name: unifi
#        - mountPath: /newunifi
#          name: unifinew
#        - mountPath: /newconfig
#          name: unifinew
        readinessProbe:
          httpGet:
            path: "/manage/account/login?redirect=%2Fmanage"
            port: http8443
            scheme: HTTPS
          failureThreshold: 40
        resources:
          limits:
            cpu: "1"
            memory: "1000Mi"
          requests:
            cpu: "0.5"
            memory: "600Mi"        
#      volumes:
#      - name: unifi
#        nfs:
#          path: /srv/nfs/unifi-controller
#          server: 172.16.30.11
#        mountOptions:
#          - local_lock=all

      volumes:
      - name: unifi
        persistentVolumeClaim:
          claimName: unifi-lhpvc
 #     - name: unifinew
 #       persistentVolumeClaim:
 #         claimName: unifi-lhpvc
          
