apiVersion: v1
kind: Service
metadata:
  name: backuppc
  labels:
    app.kubernetes.io/name: backuppc
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: backuppc
  type: ClusterIP
  
