apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ariston2mqtt
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: ariston2mqtt
    name: in-cluster
  project: default
  source:
    path: kustomize-k8s/bases/ariston2mqtt
    repoURL: repourl
    targetRevision: master
      