apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
#      selfHeal: true
  destination:
    namespace: loki
    name: in-cluster
  project: default
  source:
    path: kustomize-k8s/bases/loki
    repoURL: repourl
    targetRevision: master
      