apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare
resources:
  - namespace.yaml
  - secret.yaml
  - tunnel-origin-cert.yaml
  - configmap.yaml
  - deployment.yaml
  - deployment-amd64.yaml
