apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  loadBalancerIP: 172.16.149.38
  ports:
    - port: 1883
      protocol: TCP
      targetPort: mqtt
  selector:
    app: mosquitto
  sessionAffinity: None
  type: LoadBalancer
