apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-teslamate-psql-lhpv
  annotations:    
    k8up.io/backup: 'false'
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
