# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- origintls.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml
- ingress.yaml
- storageclass-longhorn2scbf.yaml
- storageclass.yaml
- storageclass-longhorn2scbf-2024.yaml
- storageclass-2024.yaml
- storageclass-homematic.yaml
- prometheus-rule.yaml
- servicemonitor.yaml


