apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - rule-podrestartsalert.yaml
  - origintls.yaml
  - ingress.yaml
  - rule-KubernetesVolumeOutOfDiskSpace.yaml
  - rule-KubernetesVolumeFullInFourDays.yaml
  - prometheus-kube-prometheus-kube-etcd-fixed.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: "60.3.0"
  releaseName: prometheus
  namespace: prometheus
  valuesFile: values.yaml

- name: prometheus-operator-crds
  repo: https://prometheus-community.github.io/helm-charts
  version: "12.0.0"
  releaseName: prometheus
  namespace: prometheus
  valuesFile: values-crds.yaml
