apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-photoprism-lhpv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhornscbf
  volumeMode: Filesystem
