apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-pv
  labels: 
    name: photoprism-pv
spec:
  storageClassName: piraeus-storage
  resources:
    requests:
      storage: 60Gi
  accessModes:
    - ReadWriteMany
