apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-lhpvc
  annotations:
    k8up.io/backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhornscbf
  volumeName: pvc-photoprism-lhpv
  resources:
    requests:
      storage: 60Gi

