apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
spec:
  storageClassName: piraeus-storage-replicated
  accessModes:
   - ReadWriteMany
  resources:
   requests:
    storage: 60Gi
