apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - statefulset.yaml
  - origintls.yaml
#  - servicemonitor.yaml  
#  - servicemonitor-secret.yaml
#  - rule-backuppcerrors.yaml
#  - rule-backuppc_full_backup_age.yaml
  
  
  
