apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail
resources:
  - namespace.yaml
#  - rule-podrestartsalert.yaml
#  - origintls.yaml
#  - ingress.yaml

helmCharts:
- name: promtail
  repo: https://grafana.github.io/helm-charts
  version: "6.15.5"
  releaseName: promtail
  namespace: promtail
  valuesFile: values.yaml
