apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt
resources:
  - namespace.yaml
  - statefulset.yaml
  - pvc.yaml
  - origintls.yaml
  - service.yaml
  - ingress.yaml
  
   