apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
spec:
  loadBalancerIP: 172.16.149.41
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: zigbee2mqtt
  type: LoadBalancer
  
  
