apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: kustomize-k8s/bases/argomainapp/apps
    repoURL: repourl
    targetRevision: master
    
    
    
