apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: restic
resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml
  - servicemonitor.yaml
  - rule-restic-backup_age.yaml
  
  
  
