apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-renderer
  name: grafana-renderer
spec:
  selector:
    matchLabels:
      app: grafana-renderer
  template:
    metadata:
      labels:
        app: grafana-renderer
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana-renderer
          image: docker.io/grafana/grafana-image-renderer:3.10.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http-grafana-r
              protocol: TCP
          env:
          - name: "ENABLE_METRICS"
            value: "true"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
