apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanahome-pv
  labels: 
    name: grafanahome-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - local_lock=all
  nfs:
    path: /srv/nfs/grafanahome
    server: 172.16.30.11
    