apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: nfs
  accessModes:
   - ReadWriteMany
  resources:
   requests:
    storage: 3Gi
  selector:
    matchLabels:
      name: grafanahome-pv
