apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-lhpvc
  annotations:
    k8up.io/backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-grafana-lhpv
  resources:
    requests:
      storage: 2Gi
      