apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-grafana-lhpv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
