apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: http-grafana-r
  selector:
    app: grafana-renderer
  sessionAffinity: None
  type: ClusterIP
