apiVersion: v1
kind: Namespace
metadata:
  name: k8up
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: k8up
  namespace: k8up
spec:
  chart: k8up
  repo: https://k8up-io.github.io/k8up
  targetNamespace: k8up
  version: 4.3.0
  set:
#  valuesContent: |-
#    controller:
#      kind: Deployment
#      service:
#        externalTrafficPolicy: Local


