apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-lhpvc
  annotations:
    k8up.io/backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4000Mi
      